stages:
  - build
  - test
  - deploy

build-job:
    stage: build
    script: 
        - echo "Hello, $GITLAB_USER_LOGIN!"

test-job:
    stage: test
    script:
        - echo "This is something"

deploy-job:
    stage: deploy
    script: 
        - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

environment: production 
